package workspace

import "testing"

func TestIsGeneratedDetectsMarker(t *testing.T) {
	src := "// Code generated by mockgen. DO NOT EDIT.\n\npackage pkg\n\nfunc Foo() {}\n"
	if !IsGenerated([]byte(src)) {
		t.Error("IsGenerated = false, want true for a leading DO NOT EDIT marker")
	}
}

func TestIsGeneratedNoneWhenAbsent(t *testing.T) {
	src := "// Package pkg is hand-written.\npackage pkg\n\nfunc Foo() {}\n"
	if IsGenerated([]byte(src)) {
		t.Error("IsGenerated = true, want false: no marker present")
	}
}

func TestIsGeneratedIgnoresMarkerAfterRealContent(t *testing.T) {
	src := "package pkg\n\n// Code generated by mockgen. DO NOT EDIT.\nfunc Foo() {}\n"
	if IsGenerated([]byte(src)) {
		t.Error("IsGenerated = true, want false: the marker only counts among the file's leading comments")
	}
}
